"""Structural lifecycle contract shared by independent workspaces.

This protocol intentionally contains no state or behavioural policy.  Each
format keeps its own events, transition table, reducer and Save/preview
semantics; the shell uses only this local lifecycle surface.
"""

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class WorkspaceProtocol(Protocol):
    def mount(self, host: Any) -> None: ...
    def unmount(self) -> None: ...
    def dispatch(self, event: Any, payload: Any = None) -> Any: ...
    def project(self) -> Any: ...
    def has_active_work(self) -> bool: ...
    def clear_runtime_state(self) -> Any: ...
    def enter_clean(self) -> Any: ...
